/* GENERATED by ForgeKit stamp - do not edit by hand. */
window.TRUSSFORGE_VERSION = { version: "0.13.0", built: "2026-09-02 20:28" };
(function () {
  var text = "v" + TRUSSFORGE_VERSION.version + " - updated " + TRUSSFORGE_VERSION.built;
  var els = document.querySelectorAll(".version-tag");
  for (var i = 0; i < els.length; i++) els[i].textContent = text;
})();
